# Generated by Django 6.0 on 2026-04-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FranjaPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('mensaje', models.CharField(max_length=255)),
                ('etiqueta_cta', models.CharField(blank=True, max_length=60)),
                ('url_cta', models.CharField(blank=True, max_length=255)),
                ('color_fondo', models.CharField(default='#CAFD00', max_length=7)),
                ('color_texto', models.CharField(default='#1A2200', max_length=7)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('prioridad', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Franja promocional',
                'verbose_name_plural': 'Franjas promocionales',
                'ordering': ('-prioridad', '-actualizado_en'),
            },
        ),
    ]
