# Generated by Django 6.0 on 2026-04-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_direccion_campos_espanol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=11, unique=True),
        ),
    ]
