# Generated by Django 6.0 on 2026-04-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('available_quantity__gte', 0), ('reserved_quantity__gte', 0)), name='inventory_quantities_non_negative'),
        ),
    ]
