# Generated by Django 6.0 on 2026-04-13 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_inventory_quantities_non_negative'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'verbose_name': 'Item de inventario', 'verbose_name_plural': 'Items de inventario'},
        ),
    ]
