# Generated by Django 5.1.5 on 2026-04-14 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryitem_spanish_fields_and_movimiento'),
        ('products', '0006_producto_vistas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=120, unique=True)),
                ('contacto_proveedor', models.CharField(max_length=11)),
                ('email_contacto', models.EmailField(max_length=254, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ('nombre_proveedor',),
            },
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(blank=True, max_length=80)),
                ('costo_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tiempo_reposicion_dias', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='products.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventory.proveedor')),
            ],
            options={
                'verbose_name': 'Producto proveedor',
                'verbose_name_plural': 'Productos proveedores',
                'ordering': ('producto__nombre', 'proveedor__nombre_proveedor'),
                'constraints': [models.UniqueConstraint(fields=('producto', 'proveedor'), name='producto_proveedor_unico')],
            },
        ),
    ]
