# Generated by Django 6.0 on 2026-04-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
