# Generated by Django 6.0 on 2026-04-13 22:48

import django.db.models.deletion
from django.db import migrations, models


def migrar_direccion_envio_desde_campos_shipping(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    Direccion = apps.get_model("users", "Direccion")
    Comuna = apps.get_model("users", "Comuna")

    for orden in Order.objects.filter(direccion_envio__isnull=True):
        shipping_label = getattr(orden, "shipping_label", None)
        shipping_address = getattr(orden, "shipping_address", None)
        shipping_comuna = getattr(orden, "shipping_comuna", None)
        shipping_region = getattr(orden, "shipping_region", None)

        if not shipping_address:
            continue

        direccion = (
            Direccion.objects.filter(
                usuario_id=orden.user_id,
                etiqueta=shipping_label or "",
                direccion=shipping_address,
                comuna__nombre=shipping_comuna or "",
                comuna__region__nombre=shipping_region or "",
            )
            .order_by("-id")
            .first()
        )
        if direccion:
            orden.direccion_envio_id = direccion.id
            orden.save(update_fields=["direccion_envio"])
            continue

        comuna = (
            Comuna.objects.filter(
                nombre=shipping_comuna or "",
                region__nombre=shipping_region or "",
            )
            .order_by("id")
            .first()
        )
        if not comuna:
            continue

        nueva_direccion = Direccion.objects.create(
            usuario_id=orden.user_id,
            etiqueta=(shipping_label or "Dirección envío")[:50],
            direccion=shipping_address,
            comuna_id=comuna.id,
            es_predeterminada=False,
        )
        orden.direccion_envio_id = nueva_direccion.id
        orden.save(update_fields=["direccion_envio"])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_alter_orderitem_options'),
        ('users', '0004_direccion_campos_espanol'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='direccion_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='users.direccion'),
        ),
        migrations.RunPython(migrar_direccion_envio_desde_campos_shipping, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_comuna',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_label',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_region',
        ),
    ]
