# Generated by Django 6.0 on 2026-04-13 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_marca_alter_categorias_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcion', models.CharField(blank=True, max_length=80)),
                ('energia_kcal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('proteinas_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('grasas_totales_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('grasas_saturadas_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('carbohidratos_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('azucares_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fibra_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sodio_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tabla_nutricional', to='products.producto')),
            ],
            options={
                'verbose_name': 'Tabla nutricional',
                'verbose_name_plural': 'Tablas nutricionales',
            },
        ),
    ]
