# Generated by Django 6.0 on 2026-04-13 22:01

from django.db import migrations, models


def normalizar_imagen_principal_por_producto(apps, schema_editor):
    ProductoImagen = apps.get_model("products", "ProductoImagen")

    duplicados = (
        ProductoImagen.objects
        .filter(principal=True)
        .values("producto_id")
        .order_by()
    )

    productos_procesados = set()
    for fila in duplicados:
        producto_id = fila["producto_id"]
        if producto_id in productos_procesados:
            continue
        productos_procesados.add(producto_id)

        principales = list(
            ProductoImagen.objects
            .filter(producto_id=producto_id, principal=True)
            .order_by("-id")
        )
        if len(principales) <= 1:
            continue

        mantener_id = principales[0].id
        ProductoImagen.objects.filter(
            producto_id=producto_id,
            principal=True,
        ).exclude(id=mantener_id).update(principal=False)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_tablanutricional'),
    ]

    operations = [
        migrations.RunPython(normalizar_imagen_principal_por_producto, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='productoimagen',
            constraint=models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('producto',), name='producto_una_imagen_principal'),
        ),
    ]
